server:
  port: 9092
Spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:mysql://localhost:3306/payment_service_db
    username: ${dbusername}
    password: ${dbpassword}
    jpa:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQL5Dialect
      show-sql: true
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost


resilience4j.circuitbreaker.instances.paymentServiceF:
  register-health-indicator: true
  event-consumer-buffer-size: 10
  failure-rate-threshold: 50
  minimum-number-of-calls: 5
  automatic-transition-from-open-to-half-open-enabled: true
  wait-duration-in-open-state: 5s
  permitted-number-of-calls-in-half-open-state: 3 #half open
  sliding-window-size: 10
  sliding-window-type: count_based

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always